### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by calebhailey** [sensu/network-interface-checks#1]
## Overview

 

Sensu Go network device monitoring for Linux. The Sensu Ruby plugin for network interface monitoring was downloaded over 4.2M times, making it the 5th most downloaded Sensu plugin of all time! 

## References 

- [sensu-plugins/sensu-plugins-network-checks](https://github.com/sensu-plugins/sensu-plugins-network-checks) (MIT License)
- [Telegraf `net` plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net/) (MIT License)
- [Prometheus node_exporter `netdev` module](https://github.com/prometheus/node_exporter/blob/master/collector/netdev_common.go) (Apache License 2.0)
  - [`netdev_linux`](https://github.com/prometheus/node_exporter/blob/master/collector/netdev_linux.go)
  - [`netdev_darwin`](https://github.com/prometheus/node_exporter/blob/master/collector/netdev_darwin.go)
  - [`netdev_bsd`](https://github.com/prometheus/node_exporter/blob/master/collector/netdev_bsd.go)
  - [`netdev_openbsd`](https://github.com/prometheus/node_exporter/blob/master/collector/netdev_openbsd.go)
- [Prometheus windows_exporter `net` module](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.net.md) (MIT License)
- [Datadog Agent `net` module](https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/corechecks/net/network.go) (Apache License 2.0)
- [Datadog integration docs](https://docs.datadoghq.com/integrations/network/) 

## Configuration 

 
 

- `--sample-interval` (float) number of seconds to sample (default: `3.0`)
- `--sum` (bool) add additional measurement per metric w/ "interface=all" tag (sum of all interfaces per host); _NOTE: this could break certain dashboards which calculate sums of per-interface metrics_
- `--include-interfaces` (string) comma-delimited string of interface names to include (e.g. "eth0,eth1")
- `--exclude-interfaces` (string) comma-delimited string of interface names to exclude (e.g. "lo,eth1") (default: "lo")

## Configuration Validation/Logic

 

- If `--include-interfaces` is set, and `--exclude-interfaces="lo"` (if it's the default), then ignore `--exclude-interfaces` (or reset it to `""`)
- If `--include-interfaces` is set, and `--exclude-interfaces != "lo"` raise a warning and exit status 3
- If `--sample-interval` is set to zero (`0`), only collect one sample and do not calculate the "rate" metrics
- If `--sample-interval` is set to a value greater than zero, collect two samples `--sample-interval` seconds apart, and calculate a rate that is effectively `(sample2 - sample1) / sample-inteval`

## Metrics 

 

All metrics should be output in Prometheus format. 

There are effectively four metrics (bytes, packets, errors, and dropped packets), x2 for sent/outbound and received/inbound, and x2 for collecting counters and rate gauges. 

- `bytes_sent` (counter) bytes sent
- `bytes_sent_rate` (gauge) bytes sent per second
- `bytes_recv` (counter) bytes received
- `bytes_recv_rate` (gauge) bytes received per second
- `packets_sent` (counter) packets sent
- `packets_sent_rate` (gauge) packets sent per second
- `packets_recv` (counter) packets received
- `packets_recv_rate`(gauge) packets received per second
- `err_out` (counter) outbound errors
- `err_out_rate` (gauge) outbound errors per second
- `err_in` (counter) inbound errors  
- `err_in_rate` (gauge) inbound errors per second
- `drop_out` (counter) outbound packets dropped
- `drop_out_rate` (gauge) outbound packets dropped per second
- `drop_in` (counter) incoming packets dropped 
- `drop_in_rate` (gauge) incoming packets dropped per second
- `mtu` (gauge) interface MTU configuration; _NOTE: no rate or `--sum` measurement should be generated for this metric._

## Metric Tags

 
 
 

- ~`host.name`~ To be provided via `output_metric_tags` (i.e. `{{ .name }}`) 
- `interface` collect all of the metrics defined above per interface, with the interface name as the tag value (e.g. `eth0`)

## Health Checks 

 
 

- n/a (pending support for built-in `output_metric_thresholds` support in the Sensu Go agent).

## Catalog Templates 

 
 

TODO

## TODO 

**TBD:**

 

- [x] TBD if we should automatically add the `host.name` tag, or if this should be provided via `output_metric_tags`?? Let's do it using `output_metric_tags`. 
- [ ] TBD how `rate` metrics should be calculated (e.g. a sample captured during check execution -vs- comparing the current value against the previously collected value)
- [ ] How many catalog templates should we produce for this plugin? 
- [x] Configure `telegraf` network monitoring and review metric naming scheme(s)
- [x] ~Configure `node_exporter` network monitoring and review metric naming scheme(s)~ Prometheus metric naming schema is not relevant since the target dashboard is based on Telegraf metric names. 

**Out of scope:** 

 
 
 
 

- [x] MTU healthcheck is replaced by an MTU metric and `output_metric_thresholds`
- [ ] Add support for darwin (macOS) (subset of total available linux metrics)
- [ ] Add support for bsd/openbsd (subset of total available linux metrics)
- [ ] Add support for Windows (subset of total available linux metrics)
- [ ] Bootstrap a separate plugin for network protocol metrics (e.g. TCP/UDP); including `check-banner.rb`, `check-multicast-groups.rb`,  `check-netstat-tcp.rb`, `check-ports-bind.rb`, `check-ports.rb`
- [ ] Bootstrap a separate plugin for DNS; including `check-rbl.rb`, `check-whois-*.rb`
- [ ] Bootstrap a separate plugin for `conntrack` metrics
